### PR TITLE
ci: add circleci

### PR DESCRIPTION
**Pull request by ftreguer**
Add CircleCI [#1331](https://spacelephant.tpondemand.com/restui/board.aspx?#page=board/4832170605429899055&appConfig=eyJhY2lkIjoiRjdBMEY0NkNFQzU3NjY3MThBQkQ2RDkwODEzQzU1MzMifQ==&boardPopup=task/1331/silent)

### CODE REVIEW

**Comment by Nigui** [comment]
Do we publish code coverage ?

**Comment by dlecan** [comment]
- build -> only `compile`
- test -> only `test`
- format -> become `check-format` and does only format checking
- cut dependencies between build/test/format

**Review by dlecan — CHANGES_REQUESTED** [review]
See comment in the PR

**Comment by dlecan** [comment]
> Do we publish code coverage ?

Nice catch, we should

**Comment by ftreguer** [comment]
> > Do we publish code coverage ?
> 
> Nice catch, we should

With @oclif/test we don't have coverage directly like other jest tests

**Review by dlecan — APPROVED** [review]

**Comment by Nigui** [comment]
> > > Do we publish code coverage ?
> > 
> > 
> > Nice catch, we should
> 
> With @oclif/test we don't have coverage directly like other jest tests

Why to use `@oclif/test` then ? Without `@oclif/test` it looks like that https://blog.martianwabbit.com/2018/05/25/testing-oclif-with-jest.html

**Comment by dlecan** [comment]
> > > > Do we publish code coverage ?
> > > 
> > > 
> > > Nice catch, we should
> > 
> > 
> > With @oclif/test we don't have coverage directly like other jest tests
> 
> Why to use `@oclif/test` then ? Without `@oclif/test` it looks like that https://blog.martianwabbit.com/2018/05/25/testing-oclif-with-jest.html

Let's do that in [another US](https://spacelephant.tpondemand.com/entity/1475) (internal tracker)

**Pull request merged**
